<a href="https://colab.research.google.com/github/GriffinBarber22/Gbarber22/blob/main/Barber_stats_lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
for i in range(10):
 print(i)

0
1
2
3
4
5
6
7
8
9


In [7]:
for i in range(5,8):
 print(i)

5
6
7


In [8]:
for i in range(3):
  print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


#Functions

In [9]:
def square(x):
  return x**2

In [10]:
square(5)

25

In [11]:
square(square(5))

625

In [12]:
def add_two(x):
  return x+2

In [13]:
add_two(5)

7

In [14]:
square(add_two(345))

120409

In [15]:
choice = "apple"

In [17]:
if choice == "apple":
 print("You choose apples.")

else:
  print("You did not choose apples.")

You choose apples.


In [19]:
if choice == "apple":
  print("You choose apples.")
  print("thank you, shop again!")
elif choice == "orange":
  print("You choose oranges.")
  print("thank you, shop again!")
else:
  print("You did not choose apples or oranges.")
  print("thank you, shop again!")

You choose apples.
thank you, shop again!


In [20]:
choice = input("Please enter your choice (i.e. apple):")

Please enter your choice (i.e. apple):pear


In [21]:
choice

'pear'

In [22]:
if choice == "apple":
  print("You choose apples.")
  
elif choice == "orange":
  print("You choose oranges.")
  
else:
  print("You did not choose apples or oranges.")


You did not choose apples or oranges.


In [24]:
import numpy as np

In [25]:
np.random.permutation(52)

array([ 9,  4, 44, 29, 34, 26, 19, 15,  0, 11, 13, 33, 49, 43, 48,  6, 51,
       27, 24, 35,  7, 28, 45, 46, 30, 20,  1,  5, 17, 23, 38, 41, 37, 25,
       22, 47, 50, 31, 16, 18, 40, 14, 32, 12, 42, 39, 10,  3,  8, 21,  2,
       36])

In [26]:
cards = np.random.permutation(52)

In [27]:
cards

array([ 8, 14, 46,  6, 11,  4, 24,  7, 31, 25, 32, 34, 44,  2,  9, 19, 28,
        1, 29, 26, 12, 13, 49, 38, 33, 42, 43, 50, 45, 21, 48, 17, 40,  3,
       16,  5, 36, 15, 20, 41, 22, 27,  0, 23, 39, 37, 35, 10, 30, 47, 18,
       51])

In [28]:
cards[0]

8

<img src='http://www.milefoot.com/math/discrete/counting/image/cards.png'>

In [29]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [30]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [31]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [32]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [35]:
def card_names(card_number):
  suit = card_number//13
  name = card_number%13
  return names[name] + " of " + suits[suit]

In [37]:
card_names(51)

'King of Diamonds'

In [38]:
card_names(13)

'Ace of Spades'

In [39]:
cards = np.random.permutation(52)

In [42]:
top_of_deck         = card_names(cards[0])
second_card_in_deck = card_names(cards[1])
last_card_in_deck   = card_names(cards[-1])

In [43]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Queen of Diamonds', 'Nine of Clubs', 'Seven of Hearts')

In [45]:
for i in range(5):
  print(card_names(cards[i]))

Queen of Diamonds
Nine of Clubs
Ace of Hearts
three of Diamonds
King of Clubs


In [46]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [47]:
suit = ['k','p','s','1']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [48]:
i = np.random.randint(4)
j = np.random.randint(13)

In [49]:
i,j

(2, 10)

In [50]:
card[i]

'3'

In [51]:
card[j]

'j'

In [52]:
from IPython.core.display import display, HTML

In [53]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [54]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [55]:
show_img(img)